// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // El menú se arma solo leyendo la estructura de carpetas de /docs
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
